### ISSUE TITLE
confused about startGraphicsDeadCode

### ISSUE THREAD

**Issue by patricksurry** [blondie7575/ChoplifterReverse#7]
There's a comment about how that code is never called, but `loader.s` explicitly calls it prior to calling the original loader code at $800.

If you don't call it you don't get the HUD and the ground isn't painted properly until it gets obscured by a sprite eventually.   Perhaps it was a copy-protection artifact or modified by the crack?  Weird.   In my case I patched the initial `jsr jumpInitRendering` to instead do `jsr jumpStartGraphicsDeadCode` so I can still just launch at $800 after setup.

Anyway, great fun getting the [demo loop running](https://www.youtube.com/watch?v=nsAGpuBx8YQ) on my breadboard setup.  Currently just hijacks the pageFlip routine to brute-force convert the central 75% of each frame from 7-bit reverse apple layout (280x192) to the LCD layout (240x128 with 6-bit per byte weirdly).   Need to hook up some inputs, but one day I'd like to actually port the core graphics piece properly.

If you're interested I can make a PR with some portability notes. 

![choplifter_credits](https://github.com/user-attachments/assets/dccd86c3-bebe-43eb-8d0b-3d788daf8498)
![choplifter_title](https://github.com/user-attachments/assets/f2464099-fd4c-4017-a544-a3a9a24e3fb5)

**Comment by blondie7575** [comment]
It's called dead code because only my custom loader calls it, not Dan's code. It may be that Dan's loader called it, but I didn't verify that so it qualifies as dead code according to the rules of my reverse engineer. It happened to do some stuff I needed in my loader, so I called.
